check is key (NewX_AVM-DE_PossibleBeaconTypes) available (#191)
* check is key available

```
  File "/home/vscode/.local/lib/python3.11/site-packages/fritzconnection/lib/fritzwlan.py", line 107, in get_wifi_qr_code
    security = get_beacon_security(instance, security)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/fritzconnection/lib/fritzwlan.py", line 47, in get_beacon_security
    beacontypes = set(info["NewX_AVM-DE_PossibleBeaconTypes"].split(","))
                      ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'NewX_AVM-DE_PossibleBeaconTypes'`
``

* Update fritzwlan.py

* add poroperty for get_wifi_qr_code

add Security(Enum)

* resets the quotes & rollback security check

* Unused Enum imported removed

* remove property

* Update fritzwlan.py